#!/bin/bash

echo "============================================"
echo "Spring Boot OTEL 로그 전송 확인"
echo "============================================"
echo ""

echo "1️⃣  애플리케이션 로그에서 OTEL 초기화 확인"
echo "   다음 패턴을 찾으세요:"
echo "   - 'OpenTelemetry'"
echo "   - 'OTLP'"
echo "   - 'exporter'"
echo "   - 'telemetry'"
echo ""

echo "2️⃣  port-forward로 Alloy receiver에 직접 연결된 상태에서"
echo "   로컬에서 Alloy 로그 모니터링:"
echo ""
echo "   # 새 터미널에서 실행:"
echo "   kubectl logs -n observability -l app.kubernetes.io/name=alloy-receiver -f | grep -E 'received|request|spans|logs'"
echo ""

echo "3️⃣  간단한 테스트 요청 보내기:"
echo "   # 웹 브라우저 또는 curl로 애플리케이션 접속"
echo "   curl http://localhost:8080"
echo ""
echo "   그 후 Alloy 로그에서 'received' 메시지 확인"
echo ""

echo "4️⃣  네트워크 연결 확인 (애플리케이션 실행 중):"
echo "   # 4317 또는 4318 포트로 연결 확인"
echo "   lsof -i :4317"
echo "   lsof -i :4318"
echo ""

echo "5️⃣  Spring Boot Actuator로 확인 (application.yml에 설정된 경우):"
echo "   curl http://localhost:8080/actuator/metrics | grep -i otel"
echo ""

echo "============================================"
echo "💡 디버깅 팁"
echo "============================================"
echo ""
echo "애플리케이션에 다음 설정을 추가하면 더 자세한 로그를 볼 수 있습니다:"
echo ""
echo "application.yml:"
echo "---"
echo "logging:"
echo "  level:"
echo "    io.opentelemetry: DEBUG"
echo "    io.micrometer: DEBUG"
echo ""
echo "또는 환경변수:"
echo "export OTEL_LOGS_EXPORTER=otlp"
echo "export OTEL_METRICS_EXPORTER=otlp"
echo "export OTEL_TRACES_EXPORTER=otlp"
echo "export OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://localhost:4317"
echo ""
